[inner.version]
describe = "版本号"
important = true
can_edit = false

[bot.qq]
describe = "机器人的QQ号"
important = true
can_edit = true

[bot.nickname]
describe = "机器人的昵称"
important = true
can_edit = true

[bot.alias_names]
describe = "机器人的别名列表，该选项还在调试中，暂时未生效"
important = false
can_edit = true

[groups.talk_allowed]
describe = "可以回复消息的群号码列表"
important = true
can_edit = true

[groups.talk_frequency_down]
describe = "降低回复频率的群号码列表"
important = false
can_edit = true

[groups.ban_user_id]
describe = "禁止回复和读取消息的QQ号列表"
important = false
can_edit = true

[personality.personality_core]
describe = "用一句话或几句话描述人格的核心特点，建议20字以内"
important = true
can_edit = true

[personality.personality_sides]
describe = "用一句话或几句话描述人格的一些细节，条数任意，不能为0，该选项还在调试中"
important = false
can_edit = true

[identity.identity_detail]
describe = "身份特点列表，条数任意，不能为0，该选项还在调试中"
important = false
can_edit = true

[identity.age]
describe = "年龄，单位岁"
important = false
can_edit = true

[identity.gender]
describe = "性别"
important = false
can_edit = true

[identity.appearance]
describe = "外貌特征描述，该选项还在调试中，暂时未生效"
important = false
can_edit = true

[schedule.enable_schedule_gen]
describe = "是否启用日程表"
important = false
can_edit = true

[schedule.enable_schedule_interaction]
describe = "日程表是否影响回复模式"
important = false
can_edit = true

[schedule.prompt_schedule_gen]
describe = "用几句话描述描述性格特点或行动规律，这个特征会用来生成日程表"
important = false
can_edit = true

[schedule.schedule_doing_update_interval]
describe = "日程表更新间隔，单位秒"
important = false
can_edit = true

[schedule.schedule_temperature]
describe = "日程表温度，建议0.1-0.5"
important = false
can_edit = true

[schedule.time_zone]
describe = "时区设置，可以解决运行电脑时区和国内时区不同的情况，或者模拟国外留学生日程"
important = false
can_edit = true

[platforms.nonebot-qq]
describe = "nonebot-qq适配器提供的链接"
important = true
can_edit = true

[chat.allow_focus_mode]
describe = "是否允许专注聊天状态"
important = false
can_edit = true

[chat.base_normal_chat_num]
describe = "最多允许多少个群进行普通聊天"
important = false
can_edit = true

[chat.base_focused_chat_num]
describe = "最多允许多少个群进行专注聊天"
important = false
can_edit = true

[chat.observation_context_size]
describe = "观察到的最长上下文大小，建议15，太短太长都会导致脑袋尖尖"
important = false
can_edit = true

[chat.message_buffer]
describe = "启用消息缓冲器，启用此项以解决消息的拆分问题，但会使麦麦的回复延迟"
important = false
can_edit = true

[chat.ban_words]
describe = "需要过滤的消息列表"
important = false
can_edit = true

[chat.ban_msgs_regex]
describe = "需要过滤的消息（原始消息）匹配的正则表达式，匹配到的消息将被过滤（支持CQ码）"
important = false
can_edit = true 