apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-maibot-adapter
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-maibot-adapter
spec:
  ports:
    - name: napcat-ws
      port: {{ .Values.adapter.service.port }}
      protocol: TCP
      targetPort: 8095
      {{- if eq .Values.adapter.service.type "nodePort" }}
      nodePort: {{ .Values.adapter.service.nodePort | default nil }}
      {{- end }}
  selector:
    app: {{ .Release.Name }}-maibot-adapter
  type: {{ .Values.adapter.service.type }}
